web:
  #image: clarencep/xhgui
  build: docker
  ports:
    - "8080:80"
  volumes:
    - .:/var/www/xhgui
    - ./storage/mongodb:/data/mongodb
  environment:
    - HTTP_PROXY=
    - http_proxy=
    - HTTPS_PROXY=
    - https_proxy=